version: "3"

services:


  wordpress:
    image: wordpress:5.5
    container_name: wordpress
    restart: always
    depends_on:
      - mysql
    stdin_open: true
    tty: true
    volumes:
      - ./src/plugins:/var/www/html/wp-content/plugins
      - ./src/themes:/var/www/html/wp-content/themes
    env_file: .env
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}   


  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password  
    container_name: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/configs/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    restart: always
    env_file: .env 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}    
      
  adminer:
   container_name: adm
   image: adminer 
   restart: unless-stopped    
   depends_on:      
     - mysql
   ports:      
     - "8080:8080"        
   environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     ADMINER_USERNAME: ${MYSQL_USER}
     MYSQL_DATABASE: ${MYSQL_DATABASE}
     ADMINER_PASSWORD: ${MYSQL_PASSWORD} 